openapi: 3.0.1
info:
  title: TestFileUploadAPI
  description: API Definition of TestFileUploadAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/testFileUpload
paths:
  /:
    get:
      responses:
        default:
          description: Default response
